### ISSUE TITLE
Write Regex to handle incoming messages and send proper replies

### ISSUE THREAD

**Issue by AvijitGhosh82** [kossiitkgp/kosschatbot#1]
In app.py:

```
message_text = messaging_event["message"]["text"]  # the message's text

#enter logic here 

send_message(sender_id, "got it, thanks!")
```

We need to intercept the message_text, run Regex or whatever on it and send an appropriate reply via send_message. 

For reference, see https://github.com/AvijitGhosh82/sheldonisms/blob/master/app.py#L47-L54

**Comment by AvijitGhosh82** [comment]
@pranitbauva1997

**Comment by AvijitGhosh82** [comment]
@pranitbauva1997 @DefCon-007

**Comment by madan96** [comment]
http://www.codeproject.com/Articles/18109/Building-an-AI-Chatbot-using-a-Regular-Expression
This might help.

**Comment by pranitbauva1997** [comment]
Will look into it by midnight!

**Comment by DefCon-007** [comment]
@AvijitGhosh82 : Should we close this issue as we will be using api.ai over regex

**Comment by AvijitGhosh82** [comment]
Closing issue since we use API.ai now.
